export const BASE_LABELS = {
  white_rice:    "Arroz Blanco",
  brown_rice:    "Arroz Integral",
  quinoa:        "Quinoa",
  spring_mix:    "Ensalada Orgánica",
  mixed_greens:  "Ensalada Orgánica",
};

export const PROTEIN_LABELS = {
  tuna:        "Atún",
  salmon:      "Salmón",
  shrimp:      "Camarón Cocido",
  tofu:        "Tofu",
  octopus:     "Pulpo",
  seared_tuna: "Atún Sellado",
};

export const MARINADE_LABELS = {
  citrus_marinade:        "Marinado Cítrico",
  shoyu_marinade:         "Marinado Shoyu",
  ponzu_marinade:         "Marinado Ponzu",
  spicy_marinade:         "Marinado Picante",
  sesame_marinade:        "Marinado de Sésamo",
  wasabi_marinade:        "Marinado de Wasabi",
  miso_marinade:          "Marinado de Miso",
  garlic_ginger_marinade: "Marinado de Ajo y Jengibre",
};

export const COMPLEMENT_LABELS = {
  shredded_carrots: "Zanahoria Rallada",
  cucumber:         "Pepino",
  mango:            "Mango",
  jicama:           "Jícama",
  seaweed:          "Ensalada de Alga",
  avocado:          "Aguacate",
  edamame:          "Edamame",
  red_onion:        "Cebolla Morada",
  beet:             "Betabel",
  surimi:           "Surimi",
  spicy_surimi:     "Spicy Surimi",
  kale:             "Col Rizada",
  peas:             "Chícharos",
  corn:             "Maíz",
  pineapple:        "Piña",
  chia_seeds:       "Semillas de Chía",
};

export const SAUCE_LABELS = {
  spicy_mayo:         "Mayonesa Picante",
  sweet_dressing:     "Aderezo Dulce",
  citrus_dressing:    "Aderezo Cítrico",
  red_sauce:          "Salsa Roja",
  sriracha:           "Sriracha",
  cilantro_dressing:  "Aderezo de Cilantro",
  soy_sauce:          "Salsa de Soja",
  ponzu_sauce:        "Salsa Ponzu",
  sesame_ginger:      "Aderezo de Sésamo y Jengibre",
  wasabi_vinaigrette: "Vinagreta de Wasabi",
  sweet_chili:        "Salsa de Chile Dulce",
  garlic_sriracha:    "Salsa de Ajo y Sriracha",
  avocado_lime:       "Aderezo de Aguacate y Lima",
  miso_dressing:      "Aderezo de Miso",
  yuzu_kosho:         "Salsa Yuzu Kosho",
};

export const TOPPING_LABELS = {
  black_olives:     "Aceitunas Negras",
  toasted_peanuts: "Cacahuate Tostado",
  sesame_seeds:     "Ajonjolí",
  masago:           "Masago",
  croutons:         "Crotones",
  crispy_onions:    "Cebolla Crujiente",
  nori_strips:      "Tiras de Alga Nori",
  red_pepper_flakes:"Pimienta Roja en Hojuelas",
  pickled_radish:   "Rábano Encurtido",
  toasted_coconut:  "Copos de Coco Tostado",
  pumpkin_seeds:    "Pepitas",
  furikake:         "Furikake",
};

export const ITEM_LABELS = {
  es: {
    base: BASE_LABELS,
    protein: PROTEIN_LABELS,
    marinade: MARINADE_LABELS,
    complement: COMPLEMENT_LABELS,
    sauce: SAUCE_LABELS,
    topping: TOPPING_LABELS,
  },
  en: {
    base: {
      white_rice: "White Rice",
      brown_rice: "Brown Rice",
      quinoa: "Quinoa",
      spring_mix: "Organic Salad",
      mixed_greens: "Organic Salad",
    },
    protein: {
      tuna: "Tuna",
      salmon: "Salmon",
      shrimp: "Cooked Shrimp",
      tofu: "Tofu",
      octopus: "Octopus",
      seared_tuna: "Seared Tuna",
    },
    marinade: {
      citrus_marinade: "Citrus Marinade",
      shoyu_marinade: "Shoyu Marinade",
      ponzu_marinade: "Ponzu Marinade",
      spicy_marinade: "Spicy Marinade",
      sesame_marinade: "Sesame Marinade",
      wasabi_marinade: "Wasabi Marinade",
      miso_marinade: "Miso Marinade",
      garlic_ginger_marinade: "Garlic Ginger Marinade",
    },
    complement: {
      shredded_carrots: "Shredded Carrots",
      cucumber: "Cucumber",
      mango: "Mango",
      jicama: "Jicama",
      seaweed: "Seaweed Salad",
      avocado: "Avocado",
      edamame: "Edamame",
      red_onion: "Red Onion",
      beet: "Beet",
      surimi: "Surimi",
      spicy_surimi: "Spicy Surimi",
      kale: "Kale",
      peas: "Peas",
      corn: "Corn",
      pineapple: "Pineapple",
      chia_seeds: "Chia Seeds",
    },
    sauce: {
      spicy_mayo: "Spicy Mayo",
      sweet_dressing: "Sweet Dressing",
      citrus_dressing: "Citrus Dressing",
      red_sauce: "Red Sauce",
      sriracha: "Sriracha",
      cilantro_dressing: "Cilantro Dressing",
      soy_sauce: "Soy Sauce",
      ponzu_sauce: "Ponzu Sauce",
      sesame_ginger: "Sesame Ginger Dressing",
      wasabi_vinaigrette: "Wasabi Vinaigrette",
      sweet_chili: "Sweet Chili Sauce",
      garlic_sriracha: "Garlic Sriracha Sauce",
      avocado_lime: "Avocado Lime Dressing",
      miso_dressing: "Miso Dressing",
      yuzu_kosho: "Yuzu Kosho Sauce",
    },
    topping: {
      black_olives: "Black Olives",
      toasted_peanuts: "Toasted Peanuts",
      sesame_seeds: "Sesame Seeds",
      masago: "Masago",
      croutons: "Croutons",
      crispy_onions: "Crispy Onions",
      nori_strips: "Nori Strips",
      red_pepper_flakes: "Red Pepper Flakes",
      pickled_radish: "Pickled Radish",
      toasted_coconut: "Toasted Coconut Flakes",
      pumpkin_seeds: "Pumpkin Seeds",
      furikake: "Furikake",
    },
  },
};

export const ITEM_DESCRIPTIONS = {
  es: {
    marinade: {
      citrus_marinade: "Naranja, limón y aceite de sésamo",
      shoyu_marinade: "Salsa de soya japonesa clásica",
      ponzu_marinade: "Cítrico con soya y dashi",
      spicy_marinade: "Chile fresco y jengibre picante",
      sesame_marinade: "Sésamo tostado y aceite de girasol",
      wasabi_marinade: "Toque picante suave con jengibre",
      miso_marinade: "Pasta de soya fermentada, umami",
      garlic_ginger_marinade: "Ajo fresco y jengibre picado",
    },
    sauce: {
      spicy_mayo: "Mayonesa con sriracha y limón",
      sweet_dressing: "Dulce y suave",
      citrus_dressing: "Fresco con notas de limón",
      red_sauce: "Picante intenso",
      sriracha: "Chile rojo picante",
      cilantro_dressing: "Cremoso con cilantro fresco",
      soy_sauce: "Soya japonesa para mojar",
      ponzu_sauce: "Agridulce con soya y cítrico",
      sesame_ginger: "Jengibre, sésamo y miel",
      wasabi_vinaigrette: "Toque picante suave y cítrico",
      sweet_chili: "Dulce con jalapeño y ajo",
      garlic_sriracha: "Ajo asado con chile sriracha",
      avocado_lime: "Cremoso con aguacate y lima",
      miso_dressing: "Fermentado de soya, rico en umami",
      yuzu_kosho: "Pasta japonesa de cítrico y chile",
    },
    topping: {
      black_olives: "Rebanadas suaves y saladas",
      toasted_peanuts: "Cacahuate tostado y crujiente",
      sesame_seeds: "Ajonjolí tostado, crujiente",
      masago: "Huevas pequeñas con sabor marino",
      croutons: "Cubos de pan dorados y crujientes",
      crispy_onions: "Cebolla frita en hojuelas",
      nori_strips: "Alga seca japonesa en tiras",
      red_pepper_flakes: "Pimiento rojo seco y picante",
      pickled_radish: "Rábano en vinagre, ligeramente ácido",
      toasted_coconut: "Coco tostado, toque dulce tropical",
      pumpkin_seeds: "Pepitas tostadas y saladas",
      furikake: "Mezcla japonesa: alga, sésamo y umami",
    },
  },
  en: {
    marinade: {
      citrus_marinade: "Orange, lemon, and sesame oil",
      shoyu_marinade: "Classic Japanese soy sauce",
      ponzu_marinade: "Citrus with soy and dashi",
      spicy_marinade: "Fresh chili and spicy ginger",
      sesame_marinade: "Toasted sesame and sunflower oil",
      wasabi_marinade: "Mild wasabi kick with ginger",
      miso_marinade: "Fermented soybean paste with umami",
      garlic_ginger_marinade: "Fresh garlic and chopped ginger",
    },
    sauce: {
      spicy_mayo: "Mayonnaise with sriracha and lime",
      sweet_dressing: "Smooth and lightly sweet",
      citrus_dressing: "Fresh with bright citrus notes",
      red_sauce: "Bold and spicy",
      sriracha: "Spicy red chili sauce",
      cilantro_dressing: "Creamy with fresh cilantro",
      soy_sauce: "Japanese soy sauce for dipping",
      ponzu_sauce: "Sweet and tangy soy with citrus",
      sesame_ginger: "Ginger, sesame, and honey",
      wasabi_vinaigrette: "Mild wasabi kick with citrus",
      sweet_chili: "Sweet with jalapeño and garlic",
      garlic_sriracha: "Roasted garlic with sriracha chili",
      avocado_lime: "Creamy avocado and lime",
      miso_dressing: "Fermented soy, rich in umami",
      yuzu_kosho: "Japanese citrus and chili paste",
    },
    topping: {
      black_olives: "Smooth, savory olive slices",
      toasted_peanuts: "Crunchy toasted peanuts",
      sesame_seeds: "Crunchy toasted sesame seeds",
      masago: "Tiny roe with a delicate ocean flavor",
      croutons: "Golden, crunchy bread cubes",
      crispy_onions: "Crispy onion flakes",
      nori_strips: "Dried Japanese seaweed strips",
      red_pepper_flakes: "Dried, spicy red pepper",
      pickled_radish: "Slightly tangy pickled radish",
      toasted_coconut: "Toasted coconut with a tropical sweetness",
      pumpkin_seeds: "Toasted and salted pumpkin seeds",
      furikake: "Japanese seaweed, sesame, and umami blend",
    },
  },
};

export const getItemLabel = (category, id, language = "es") => {
  if (!id) return "";
  return ITEM_LABELS[language]?.[category]?.[id] || ITEM_LABELS.es?.[category]?.[id] || id;
};

export const getItemDescription = (category, id, language = "es") =>
  ITEM_DESCRIPTIONS[language]?.[category]?.[id]
  || ITEM_DESCRIPTIONS.es?.[category]?.[id]
  || "";
