import mongoose from "mongoose";

// Un bowl dentro de la promo "2x1 en Bowls" (kind: "promo2x1" abajo) — sin
// proteína propia (la comparten los 2, ver `protein` en cartLineSchema).
const promo2x1BowlSchema = new mongoose.Schema(
  {
    base:        { type: String, default: null },
    bases:       { type: [String], default: [] },
    marinades:   { type: [String], default: [] },
    complements: { type: [String], default: [] },
    sauces:      { type: [String], default: [] },
    toppings:    { type: [String], default: [] },
  },
  { _id: false }
);

// Una línea del carrito de cliente/kiosco: un bowl personalizado completo, un
// artículo del catálogo (bebida, entrada, bowl de la casa) con cantidad, o la
// promo "2x1 en Bowls". Convive con los campos planos de abajo (que siguen
// siendo lo único que usa el POS/personal) — un pedido de cliente nuevo llena
// `cartItems` y además replica el primer bowl en los campos planos, por
// compatibilidad con cualquier lector que aún no distinga carritos.
const cartLineSchema = new mongoose.Schema(
  {
    kind: { type: String, enum: ["bowl", "item", "promo2x1"], required: true },
    // Campos de bowl (kind: "bowl")
    base:        { type: String, default: null },
    bases:       { type: [String], default: [] },
    proteins:    { type: [String], default: [] },
    bowlSize:    { type: String, enum: ["normal", "large"], default: "normal" },
    marinades:   { type: [String], default: [] },
    complements: { type: [String], default: [] },
    sauces:      { type: [String], default: [] },
    toppings:    { type: [String], default: [] },
    extraScoopProteins: { type: [String], default: [] },
    // Campos de artículo de catálogo (kind: "item")
    catalogId: { type: String, default: null },
    name:      { type: String, default: null },
    // Elecciones del Combo Palace (kind: "item", catalogId: "combo-palace")
    comboBowlId:     { type: String, default: null },
    comboDrinkId:    { type: String, default: null },
    comboRiceCakeId: { type: String, default: null },
    // Campos de la promo "2x1 en Bowls" (kind: "promo2x1") — 1 proteína
    // compartida entre los 2 bowls (60 g + 60 g = 120 g).
    protein: { type: String, default: null },
    bowls:   { type: [promo2x1BowlSchema], default: [] },
    // Compartidos
    price: { type: Number, default: 0 },
    qty:   { type: Number, default: 1 },
  },
  { _id: false }
);

const orderSchema = new mongoose.Schema(
  {
    // Customer-side orders: user is set. POS orders: staffId is set.
    user:    { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    staffId: { type: mongoose.Schema.Types.ObjectId, ref: "StaffUser" },

    // Stable identifier generated by the POS device. Retries with the same id
    // return the original sale instead of charging, deducting stock, or
    // awarding points twice.
    clientOrderId: { type: String, default: null, trim: true, maxlength: 100 },

    // Guest orders are protected with a high-entropy bearer secret. Only its
    // SHA-256 digest is persisted and it is never serialized in API responses.
    guestAccessTokenHash: { type: String, default: null, select: false },

    // Bowl-builder fields (customer orders)
    base:        { type: String, default: null },
    // Cuando el cliente pide "mitad y mitad", trae las 2 bases elegidas —
    // `base` sigue guardando la primera para no romper a quien solo lea ese
    // campo (KDS viejo, reportes, etc.).
    bases:       { type: [String], default: [] },
    protein:     { type: String, default: null },
    proteins:    { type: [String], default: [] },
    bowlSize:    { type: String, enum: ["normal", "large"], default: "normal" },
    proteinUpcharge: { type: Number, default: 0 },
    marinades:   { type: [String], default: [] },
    complements: { type: [String], default: [] },
    sauces:      { type: [String], default: [] },
    toppings:    { type: [String], default: [] },
    // Porciones extra (40 g, $40 c/u) de una proteína ya elegida — puede
    // repetir el mismo id (dos scoops extra de salmón = ["salmon","salmon"]).
    extraScoopProteins: { type: [String], default: [] },

    // POS orders: flat item list [{name, price, qty}]
    items: { type: Array, default: [] },

    // Carrito de cliente/kiosco con 1 o más bowls y/o artículos del menú —
    // ver cartLineSchema arriba. Vacío para pedidos POS y para pedidos de
    // cliente de antes de esta función (que solo usan los campos planos).
    cartItems: { type: [cartLineSchema], default: [] },

    // Shared optional fields
    customer: { type: String, default: null }, // "Table 4", "Walk-in", customer name
    phone:    { type: String, default: null },
    notes:    { type: String, default: null },
    fulfillment: {
      type: String,
      enum: ["pickup", "dine_in", "delivery"],
      default: "pickup",
    },
    paymentMethod: {
      type: String,
      enum: ["pay_at_pickup", "cash", "card_terminal", "online"],
      default: "pay_at_pickup",
    },
    paymentStatus: {
      type: String,
      enum: ["pending", "paid"],
      default: "pending",
    },
    // Id y link del cargo generado por el procesador de pagos en línea
    // (Openpay/BBVA desde ago 2026; antes Clip — el nombre del campo ya no
    // referencia a ningún proveedor en particular).
    paymentRequestId: { type: String, default: null },
    paymentRequestUrl: { type: String, default: null },
    source:   { type: String, enum: ["online", "pos", "whatsapp"], default: "online" },
    total:    { type: Number, default: null },  // in MXN

    // Canal de publicidad por el que el cliente dice haber conocido el
    // restaurante (capturado por el cajero en el POS). Ver REFERRAL_SOURCES
    // en backend/config/posCatalog.js. Opcional — null si no se preguntó.
    referralSource:      { type: String, default: null },
    referralSourceOther: { type: String, default: null },

    // Pricing — always computed server-side, never trusted from the client
    subtotal: { type: Number, default: null },
    tax:      { type: Number, default: null },

    // Promo codes
    promoCode:      { type: String, default: null },
    discountAmount: { type: Number, default: 0 },

    // Scheduled pickup
    scheduledPickupTime: { type: Date, default: null },
    isScheduled:         { type: Boolean, default: false },

    // Loyalty
    loyaltyPointsEarned: { type: Number, default: 0 },
    loyaltyCreditLedgerVersion: { type: Number, default: 0 },
    loyaltyCreditAppliedAt: { type: Date, default: null },
    pointsRedeemed:      { type: Number, default: 0 },
    rewardRedemption: { type: mongoose.Schema.Types.ObjectId, ref: "Redemption", default: null },
    rewardCode:       { type: String, default: null },
    // Concrete topping selected at the POS for the extra_topping reward. It is
    // also counted as one additional inventory portion during reconciliation.
    rewardExtraTopping: { type: String, default: null },

    // Customer cancellation reconciliation. The timestamps make a cancelled
    // order safely retryable if one of the compensating updates is interrupted.
    cancelledAt:             { type: Date, default: null },
    pointsRefundedAt:        { type: Date, default: null },
    promoUseReleasedAt:      { type: Date, default: null },
    cancellationReversedAt:  { type: Date, default: null },
    inventoryRestoredAt:     { type: Date, default: null },
    loyaltyReversedAt:       { type: Date, default: null },
    rewardRestoredAt:        { type: Date, default: null },
    posCancellationReversedAt: { type: Date, default: null },

    // Inventory deduction
    ingredientsDeducted: { type: Boolean, default: false },

    status: {
      type: String,
      enum: ["pending", "preparing", "ready", "completed", "cancelled"],
      default: "pending",
    },
  },
  {
    timestamps: true,
    toJSON: {
      transform: (_doc, ret) => {
        delete ret.guestAccessTokenHash;
        return ret;
      },
    },
  }
);

orderSchema.index(
  { clientOrderId: 1 },
  {
    unique: true,
    name: "unique_client_order_id",
    partialFilterExpression: { clientOrderId: { $type: "string" } },
  }
);

export default mongoose.model("Order", orderSchema);
