import mongoose from "mongoose";

const orderSchema = new mongoose.Schema(
  {
    // Customer-side orders: user is set. POS orders: staffId is set.
    user:    { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    staffId: { type: mongoose.Schema.Types.ObjectId, ref: "StaffUser" },

    // Stable identifier generated by the POS device. Retries with the same id
    // return the original sale instead of charging, deducting stock, or
    // awarding points twice.
    clientOrderId: { type: String, default: null, trim: true, maxlength: 100 },

    // Guest orders are protected with a high-entropy bearer secret. Only its
    // SHA-256 digest is persisted and it is never serialized in API responses.
    guestAccessTokenHash: { type: String, default: null, select: false },

    // Bowl-builder fields (customer orders)
    base:        { type: String, default: null },
    protein:     { type: String, default: null },
    proteins:    { type: [String], default: [] },
    bowlSize:    { type: String, enum: ["normal", "large"], default: "normal" },
    proteinUpcharge: { type: Number, default: 0 },
    marinades:   { type: [String], default: [] },
    complements: { type: [String], default: [] },
    sauces:      { type: [String], default: [] },
    toppings:    { type: [String], default: [] },

    // POS orders: flat item list [{name, price, qty}]
    items: { type: Array, default: [] },

    // Shared optional fields
    customer: { type: String, default: null }, // "Table 4", "Walk-in", customer name
    phone:    { type: String, default: null },
    notes:    { type: String, default: null },
    fulfillment: {
      type: String,
      enum: ["pickup", "dine_in", "delivery"],
      default: "pickup",
    },
    paymentMethod: {
      type: String,
      enum: ["pay_at_pickup", "cash", "card_terminal", "online"],
      default: "pay_at_pickup",
    },
    paymentStatus: {
      type: String,
      enum: ["pending", "paid"],
      default: "pending",
    },
    clipPaymentRequestId: { type: String, default: null },
    clipPaymentUrl:       { type: String, default: null },
    source:   { type: String, enum: ["online", "pos"], default: "online" },
    total:    { type: Number, default: null },  // in MXN

    // Pricing — always computed server-side, never trusted from the client
    subtotal: { type: Number, default: null },
    tax:      { type: Number, default: null },

    // Promo codes
    promoCode:      { type: String, default: null },
    discountAmount: { type: Number, default: 0 },

    // Scheduled pickup
    scheduledPickupTime: { type: Date, default: null },
    isScheduled:         { type: Boolean, default: false },

    // Loyalty
    loyaltyPointsEarned: { type: Number, default: 0 },
    loyaltyCreditLedgerVersion: { type: Number, default: 0 },
    loyaltyCreditAppliedAt: { type: Date, default: null },
    pointsRedeemed:      { type: Number, default: 0 },
    rewardRedemption: { type: mongoose.Schema.Types.ObjectId, ref: "Redemption", default: null },
    rewardCode:       { type: String, default: null },
    // Concrete topping selected at the POS for the extra_topping reward. It is
    // also counted as one additional inventory portion during reconciliation.
    rewardExtraTopping: { type: String, default: null },

    // Customer cancellation reconciliation. The timestamps make a cancelled
    // order safely retryable if one of the compensating updates is interrupted.
    cancelledAt:             { type: Date, default: null },
    pointsRefundedAt:        { type: Date, default: null },
    promoUseReleasedAt:      { type: Date, default: null },
    cancellationReversedAt:  { type: Date, default: null },
    inventoryRestoredAt:     { type: Date, default: null },
    loyaltyReversedAt:       { type: Date, default: null },
    rewardRestoredAt:        { type: Date, default: null },
    posCancellationReversedAt: { type: Date, default: null },

    // Inventory deduction
    ingredientsDeducted: { type: Boolean, default: false },

    status: {
      type: String,
      enum: ["pending", "preparing", "ready", "completed", "cancelled"],
      default: "pending",
    },
  },
  {
    timestamps: true,
    toJSON: {
      transform: (_doc, ret) => {
        delete ret.guestAccessTokenHash;
        return ret;
      },
    },
  }
);

orderSchema.index(
  { clientOrderId: 1 },
  {
    unique: true,
    name: "unique_client_order_id",
    partialFilterExpression: { clientOrderId: { $type: "string" } },
  }
);

export default mongoose.model("Order", orderSchema);
